[package]
name = "schamars-zod"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12"
serde = "1"

[dependencies.schemars]
version = "0.8"
features = ["chrono"]

[dev-dependencies]
serde_json = "1"
chrono = "0.4"